export const Countries = [
    {
      id: 1,
      ulke: "United States",
      cca2: "US",
      bayrak: "🇺🇸",
      ulke_kodu: "1",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 2,
      ulke: "Afghanistan",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "AF",
      bayrak: "🇦🇫",
      ulke_kodu: "93",
    },
    {
      id: 3,
      ulke: "Germany",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "DE",
      bayrak: "🇩🇪",
      ulke_kodu: "49",
    },
    {
      id: 4,
      ulke: "Andorra",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "AD",
      bayrak: "🇦🇩",
      ulke_kodu: "376",
    },
    {
      id: 5,
      ulke: "Angola",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "AO",
      bayrak: "🇦🇴",
      ulke_kodu: "244",
    },
    {
      id: 6,
      ulke: "Antigua and Barbuda",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "AG",
      bayrak: "🇦🇬",
      ulke_kodu: "1268",
    },
    {
      id: 7,
      ulke: "Argentina",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "AR",
      bayrak: "🇦🇷",
      ulke_kodu: "54",
    },
    {
      id: 8,
      ulke: "Albania",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "AL",
      bayrak: "🇦🇱",
      ulke_kodu: "355",
    },
    {
      id: 9,
      ulke: "Australia",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "AU",
      bayrak: "🇦🇺",
      ulke_kodu: "61",
    },
    {
      id: 10,
      ulke: "Austria",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "AT",
      bayrak: "🇦🇹",
      ulke_kodu: "43",
    },
    {
      id: 11,
      ulke: "Azerbaijan",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "AZ",
      bayrak: "🇦🇿",
      ulke_kodu: "994",
    },
    {
      id: 12,
      ulke: "Bahamas",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BS",
      bayrak: "🇧🇸",
      ulke_kodu: "1242",
    },
    {
      id: 13,
      ulke: "Bahrain",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "BH",
      bayrak: "🇧🇭",
      ulke_kodu: "973",
    },
    {
      id: 14,
      ulke: "Bangladesh",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "BD",
      bayrak: "🇧🇩",
      ulke_kodu: "880",
    },
    {
      id: 15,
      ulke: "Barbados",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BB",
      bayrak: "🇧🇧",
      ulke_kodu: "1246",
    },
    {
      id: 16,
      ulke: "Samoa",
      cca2: "WS",
      bayrak: "🇼🇸",
      ulke_kodu: "685",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 17,
      ulke: "Belarus",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
      cca2: "BY",
      bayrak: "🇧🇾",
      ulke_kodu: "375",
    },
    {
      id: 18,
      ulke: "Belgium",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BE",
      bayrak: "🇧🇪",
      ulke_kodu: "32",
    },
    {
      id: 19,
      ulke: "Belize",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BZ",
      bayrak: "🇧🇿",
      ulke_kodu: "501",
    },
    {
      id: 20,
      ulke: "Benin",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "BJ",
      bayrak: "🇧🇯",
      ulke_kodu: "229",
    },
    {
      id: 21,
      ulke: "Bhutan",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "BT",
      bayrak: "🇧🇹",
      ulke_kodu: "975",
    },
    {
      id: 22,
      ulke: "United Arab Emirates",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "AE",
      bayrak: "🇦🇪",
      ulke_kodu: "971",
    },
    {
      id: 23,
      ulke: "Bolivia",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BO",
      bayrak: "🇧🇴",
      ulke_kodu: "591",
    },
    {
      id: 24,
      ulke: "Bosnia and Herzegovina",
      umuma_mahsus: "✅ (UP TO 60 DAYS)",
      resmi_pasaport: "✅ (UP TO 60 DAYS)",
      e_vize: "⛔️",
      cca2: "BA",
      bayrak: "🇧🇦",
      ulke_kodu: "387",
    },
    {
      id: 25,
      ulke: "Botswana",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "BW",
      bayrak: "🇧🇼",
      ulke_kodu: "267",
    },
    {
      id: 26,
      ulke: "Brazil",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BR",
      bayrak: "🇧🇷",
      ulke_kodu: "55",
    },
    {
      id: 27,
      ulke: "Brunei",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "BN",
      bayrak: "🇧🇳",
      ulke_kodu: "673",
    },
    {
      id: 28,
      ulke: "Bulgaria",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
      cca2: "BG",
      bayrak: "🇧🇬",
      ulke_kodu: "359",
    },
    {
      id: 29,
      ulke: "Burkina Faso",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "BF",
      bayrak: "🇧🇫",
      ulke_kodu: "226",
    },
    {
      id: 30,
      ulke: "Burundi",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "BI",
      bayrak: "🇧🇮",
      ulke_kodu: "257",
    },
    {
      id: 31,
      ulke: "Cape Verde",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CV",
      bayrak: "🇨🇻",
      ulke_kodu: "238",
    },
    {
      id: 32,
      ulke: "Algeria",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "DZ",
      bayrak: "🇩🇿",
      ulke_kodu: "213",
    },
    {
      id: 33,
      ulke: "Djibouti",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "DJ",
      bayrak: "🇩🇯",
      ulke_kodu: "253",
    },
    {
      id: 34,
      ulke: "Chad",
      cca2: "TD",
      bayrak: "🇹🇩",
      ulke_kodu: "235",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 35,
      ulke: "Czechia",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "CZ",
      bayrak: "🇨🇿",
      ulke_kodu: "420",
    },
    {
      id: 36,
      ulke: "China",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CN",
      bayrak: "🇨🇳",
      ulke_kodu: "86",
    },
    {
      id: 37,
      ulke: "Denmark",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "DK",
      bayrak: "🇩🇰",
      ulke_kodu: "45",
    },
    {
      id: 38,
      ulke: "Timor-Leste",
      cca2: "TL",
      bayrak: "🇹🇱",
      ulke_kodu: "670",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 39,
      ulke: "Dominica",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "DM",
      bayrak: "🇩🇲",
      ulke_kodu: "1767",
    },
    {
      id: 40,
      ulke: "Dominican Republic",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "DO",
      bayrak: "🇩🇴",
      ulke_kodu: "1809",
    },
    {
      id: 41,
      ulke: "Ecuador",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "EC",
      bayrak: "🇪🇨",
      ulke_kodu: "593",
    },
    {
      id: 42,
      ulke: "Equatorial Guinea",
      cca2: "GQ",
      bayrak: "🇬🇶",
      ulke_kodu: "240",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 43,
      ulke: "El Salvador",
      cca2: "SV",
      bayrak: "🇸🇻",
      ulke_kodu: "503",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 44,
      ulke: "Indonesia",
      cca2: "ID",
      bayrak: "🇮🇩",
      ulke_kodu: "62",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 45,
      ulke: "Eritrea",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "ER",
      bayrak: "🇪🇷",
      ulke_kodu: "291",
    },
    {
      id: 46,
      ulke: "Armenia",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "AM",
      bayrak: "🇦🇲",
      ulke_kodu: "374",
    },
    {
      id: 47,
      ulke: "Estonia",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "EE",
      bayrak: "🇪🇪",
      ulke_kodu: "372",
    },
    {
      id: 48,
      ulke: "Ethiopia",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "ET",
      bayrak: "🇪🇹",
      ulke_kodu: "251",
    },
    {
      id: 49,
      ulke: "Morocco",
      cca2: "MA",
      bayrak: "🇲🇦",
      ulke_kodu: "212",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 50,
      ulke: "Fiji",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "FJ",
      bayrak: "🇫🇯",
      ulke_kodu: "679",
    },
    {
      id: 51,
      ulke: "Ivory Coast",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CI",
      bayrak: "🇨🇮",
      ulke_kodu: "225",
    },
    {
      id: 52,
      ulke: "Philippines",
      cca2: "PH",
      bayrak: "🇵🇭",
      ulke_kodu: "63",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 53,
      ulke: "FILISTIN",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 54,
      ulke: "Finland",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "FI",
      bayrak: "🇫🇮",
      ulke_kodu: "358",
    },
    {
      id: 55,
      ulke: "France",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "FR",
      bayrak: "🇫🇷",
      ulke_kodu: "33",
    },
    {
      id: 56,
      ulke: "Gabon",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "GA",
      bayrak: "🇬🇦",
      ulke_kodu: "241",
    },
    {
      id: 57,
      ulke: "Gambia",
      cca2: "GM",
      bayrak: "🇬🇲",
      ulke_kodu: "220",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 58,
      ulke: "Ghana",
      cca2: "GH",
      bayrak: "🇬🇭",
      ulke_kodu: "233",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 59,
      ulke: "Guinea",
      cca2: "GN",
      bayrak: "🇬🇳",
      ulke_kodu: "224",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 60,
      ulke: "Guinea-Bissau",
      cca2: "GW",
      bayrak: "🇬🇼",
      ulke_kodu: "245",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 61,
      ulke: "Grenada",
      cca2: "GD",
      bayrak: "🇬🇩",
      ulke_kodu: "1473",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 62,
      ulke: "Guatemala",
      cca2: "GT",
      bayrak: "🇬🇹",
      ulke_kodu: "502",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 63,
      ulke: "Guyana",
      cca2: "GY",
      bayrak: "🇬🇾",
      ulke_kodu: "592",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 64,
      ulke: "South Africa",
      cca2: "ZA",
      bayrak: "🇿🇦",
      ulke_kodu: "27",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 65,
      ulke: "Georgia",
      cca2: "GE",
      bayrak: "🇬🇪",
      ulke_kodu: "995",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 66,
      ulke: "South Sudan",
      cca2: "SS",
      bayrak: "🇸🇸",
      ulke_kodu: "211",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 67,
      ulke: "Haiti",
      cca2: "HT",
      bayrak: "🇭🇹",
      ulke_kodu: "509",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 68,
      ulke: "Croatia",
      cca2: "HR",
      bayrak: "🇭🇷",
      ulke_kodu: "385",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 69,
      ulke: "India",
      cca2: "IN",
      bayrak: "🇮🇳",
      ulke_kodu: "91",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 70,
      ulke: "Netherlands",
      cca2: "NL",
      bayrak: "🇳🇱",
      ulke_kodu: "31",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 71,
      ulke: "Honduras",
      cca2: "HN",
      bayrak: "🇭🇳",
      ulke_kodu: "504",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 72,
      ulke: "HONGKONG (SAR)",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 73,
      ulke: "HONGKONG (British National Overseas)",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 74,
      ulke: "Iraq",
      cca2: "IQ",
      bayrak: "🇮🇶",
      ulke_kodu: "964",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 75,
      ulke: "United Kingdom",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "GB",
      bayrak: "🇬🇧",
      ulke_kodu: "44",
    },
    {
      id: 76,
      ulke: "Iran",
      cca2: "IR",
      bayrak: "🇮🇷",
      ulke_kodu: "98",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 77,
      ulke: "Ireland",
      cca2: "IE",
      bayrak: "🇮🇪",
      ulke_kodu: "353",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 78,
      ulke: "Spain",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "ES",
      bayrak: "🇪🇸",
      ulke_kodu: "34",
    },
    {
      id: 79,
      ulke: "Israel",
      cca2: "IL",
      bayrak: "🇮🇱",
      ulke_kodu: "972",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 80,
      ulke: "Sweden",
      cca2: "SE",
      bayrak: "🇸🇪",
      ulke_kodu: "46",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 81,
      ulke: "Switzerland",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "CH",
      bayrak: "🇨🇭",
      ulke_kodu: "41",
    },
    {
      id: 82,
      ulke: "Italy",
      cca2: "IT",
      bayrak: "🇮🇹",
      ulke_kodu: "39",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 83,
      ulke: "Iceland",
      cca2: "IS",
      bayrak: "🇮🇸",
      ulke_kodu: "354",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 84,
      ulke: "Jamaica",
      cca2: "JM",
      bayrak: "🇯🇲",
      ulke_kodu: "1876",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 85,
      ulke: "Japan",
      cca2: "JP",
      bayrak: "🇯🇵",
      ulke_kodu: "81",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 86,
      ulke: "Cambodia",
      cca2: "KH",
      bayrak: "🇰🇭",
      ulke_kodu: "855",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 87,
      ulke: "Cameroon",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CM",
      bayrak: "🇨🇲",
      ulke_kodu: "237",
    },
    {
      id: 88,
      ulke: "Canada",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "CA",
      bayrak: "🇨🇦",
      ulke_kodu: "1",
    },
    {
      id: 89,
      ulke: "Montenegro",
      cca2: "ME",
      bayrak: "🇲🇪",
      ulke_kodu: "382",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 90,
      ulke: "Qatar",
      cca2: "QA",
      bayrak: "🇶🇦",
      ulke_kodu: "974",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 91,
      ulke: "Kazakhstan",
      cca2: "KZ",
      bayrak: "🇰🇿",
      ulke_kodu: "76",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 92,
      ulke: "Kenya",
      cca2: "KE",
      bayrak: "🇰🇪",
      ulke_kodu: "254",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 93,
      ulke: "Cyprus",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "CY",
      bayrak: "🇨🇾",
      ulke_kodu: "357",
    },
    {
      id: 94,
      ulke: "Kyrgyzstan",
      cca2: "KG",
      bayrak: "🇰🇬",
      ulke_kodu: "996",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 95,
      ulke: "Kiribati",
      cca2: "KI",
      bayrak: "🇰🇮",
      ulke_kodu: "686",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 96,
      ulke: "KKTC",
      umuma_mahsus: "✅ COMPLETELY",
      resmi_pasaport: "✅ COMPLETELY",
      e_vize: "⛔️",
    },
    {
      id: 97,
      ulke: "Colombia",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "CO",
      bayrak: "🇨🇴",
      ulke_kodu: "57",
    },
    {
      id: 98,
      ulke: "Comoros",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "KM",
      bayrak: "🇰🇲",
      ulke_kodu: "269",
    },
    {
      id: 99,
      ulke: "Republic of the Congo",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CG",
      bayrak: "🇨🇬",
      ulke_kodu: "242",
    },
    {
      id: 100,
      ulke: "DR Congo",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CD",
      bayrak: "🇨🇩",
      ulke_kodu: "243",
    },
    {
      id: 101,
      ulke: "South Korea",
      cca2: "KR",
      bayrak: "🇰🇷",
      ulke_kodu: "82",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 102,
      ulke: "North Korea",
      cca2: "KP",
      bayrak: "🇰🇵",
      ulke_kodu: "850",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 103,
      ulke: "KOSOVA",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 104,
      ulke: "Costa Rica",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
      cca2: "CR",
      bayrak: "🇨🇷",
      ulke_kodu: "506",
    },
    {
      id: 105,
      ulke: "Kuwait",
      cca2: "KW",
      bayrak: "🇰🇼",
      ulke_kodu: "965",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 106,
      ulke: "KUZEY MARIANA ADALARI",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 107,
      ulke: "Cuba",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "CU",
      bayrak: "🇨🇺",
      ulke_kodu: "53",
    },
    {
      id: 108,
      ulke: "Laos",
      cca2: "LA",
      bayrak: "🇱🇦",
      ulke_kodu: "856",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 109,
      ulke: "Lesotho",
      cca2: "LS",
      bayrak: "🇱🇸",
      ulke_kodu: "266",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 110,
      ulke: "Latvia",
      cca2: "LV",
      bayrak: "🇱🇻",
      ulke_kodu: "371",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 111,
      ulke: "Liberia",
      cca2: "LR",
      bayrak: "🇱🇷",
      ulke_kodu: "231",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 112,
      ulke: "Libya",
      cca2: "LY",
      bayrak: "🇱🇾",
      ulke_kodu: "218",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 113,
      ulke: "Liechtenstein",
      cca2: "LI",
      bayrak: "🇱🇮",
      ulke_kodu: "423",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 114,
      ulke: "Lithuania",
      cca2: "LT",
      bayrak: "🇱🇹",
      ulke_kodu: "370",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 115,
      ulke: "Lebanon",
      cca2: "LB",
      bayrak: "🇱🇧",
      ulke_kodu: "961",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 116,
      ulke: "Luxembourg",
      cca2: "LU",
      bayrak: "🇱🇺",
      ulke_kodu: "352",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 117,
      ulke: "Hungary",
      cca2: "HU",
      bayrak: "🇭🇺",
      ulke_kodu: "36",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 118,
      ulke: "Madagascar",
      cca2: "MG",
      bayrak: "🇲🇬",
      ulke_kodu: "261",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 119,
      ulke: "MAKAU ÃIB",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 120,
      ulke: "Macedonia",
      cca2: "MK",
      bayrak: "🇲🇰",
      ulke_kodu: "389",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 121,
      ulke: "Malawi",
      cca2: "MW",
      bayrak: "🇲🇼",
      ulke_kodu: "265",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 122,
      ulke: "Maldives",
      cca2: "MV",
      bayrak: "🇲🇻",
      ulke_kodu: "960",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 123,
      ulke: "Malaysia",
      cca2: "MY",
      bayrak: "🇲🇾",
      ulke_kodu: "60",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 124,
      ulke: "Mali",
      cca2: "ML",
      bayrak: "🇲🇱",
      ulke_kodu: "223",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 125,
      ulke: "Malta",
      cca2: "MT",
      bayrak: "🇲🇹",
      ulke_kodu: "356",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
    },
    {
      id: 126,
      ulke: "Marshall Islands",
      cca2: "MH",
      bayrak: "🇲🇭",
      ulke_kodu: "692",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 127,
      ulke: "Mauritius",
      cca2: "MU",
      bayrak: "🇲🇺",
      ulke_kodu: "230",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 128,
      ulke: "Mexico",
      cca2: "MX",
      bayrak: "🇲🇽",
      ulke_kodu: "52",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 129,
      ulke: "Egypt",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "EG",
      bayrak: "🇪🇬",
      ulke_kodu: "20",
    },
    {
      id: 130,
      ulke: "Micronesia",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
      cca2: "FM",
      bayrak: "🇫🇲",
      ulke_kodu: "691",
    },
    {
      id: 131,
      ulke: "Mongolia",
      cca2: "MN",
      bayrak: "🇲🇳",
      ulke_kodu: "976",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 132,
      ulke: "Moldova",
      cca2: "MD",
      bayrak: "🇲🇩",
      ulke_kodu: "373",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 133,
      ulke: "Monaco",
      cca2: "MC",
      bayrak: "🇲🇨",
      ulke_kodu: "377",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 134,
      ulke: "Mauritania",
      cca2: "MR",
      bayrak: "🇲🇷",
      ulke_kodu: "222",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 135,
      ulke: "Mozambique",
      cca2: "MZ",
      bayrak: "🇲🇿",
      ulke_kodu: "258",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 136,
      ulke: "Myanmar",
      cca2: "MM",
      bayrak: "🇲🇲",
      ulke_kodu: "95",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 137,
      ulke: "Namibia",
      cca2: "NA",
      bayrak: "🇳🇦",
      ulke_kodu: "264",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 138,
      ulke: "Nauru",
      cca2: "NR",
      bayrak: "🇳🇷",
      ulke_kodu: "674",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 139,
      ulke: "Nepal",
      cca2: "NP",
      bayrak: "🇳🇵",
      ulke_kodu: "977",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 140,
      ulke: "Niger",
      cca2: "NE",
      bayrak: "🇳🇪",
      ulke_kodu: "227",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 141,
      ulke: "Nigeria",
      cca2: "NG",
      bayrak: "🇳🇬",
      ulke_kodu: "234",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 142,
      ulke: "Nicaragua",
      cca2: "NI",
      bayrak: "🇳🇮",
      ulke_kodu: "505",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 143,
      ulke: "Norway",
      cca2: "NO",
      bayrak: "🇳🇴",
      ulke_kodu: "47",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 144,
      ulke: "Central African Republic",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "CF",
      bayrak: "🇨🇫",
      ulke_kodu: "236",
    },
    {
      id: 145,
      ulke: "Uzbekistan",
      cca2: "UZ",
      bayrak: "🇺🇿",
      ulke_kodu: "998",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 146,
      ulke: "Pakistan",
      cca2: "PK",
      bayrak: "🇵🇰",
      ulke_kodu: "92",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 147,
      ulke: "Palau",
      cca2: "PW",
      bayrak: "🇵🇼",
      ulke_kodu: "680",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 148,
      ulke: "Panama",
      cca2: "PA",
      bayrak: "🇵🇦",
      ulke_kodu: "507",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 149,
      ulke: "Papua New Guinea",
      cca2: "PG",
      bayrak: "🇵🇬",
      ulke_kodu: "675",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 150,
      ulke: "Paraguay",
      cca2: "PY",
      bayrak: "🇵🇾",
      ulke_kodu: "595",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 151,
      ulke: "Peru",
      cca2: "PE",
      bayrak: "🇵🇪",
      ulke_kodu: "51",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 152,
      ulke: "Poland",
      cca2: "PL",
      bayrak: "🇵🇱",
      ulke_kodu: "48",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 153,
      ulke: "Portugal",
      cca2: "PT",
      bayrak: "🇵🇹",
      ulke_kodu: "351",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 154,
      ulke: "Romania",
      cca2: "RO",
      bayrak: "🇷🇴",
      ulke_kodu: "40",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 155,
      ulke: "Rwanda",
      cca2: "RW",
      bayrak: "🇷🇼",
      ulke_kodu: "250",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 156,
      ulke: "Russia",
      cca2: "RU",
      bayrak: "🇷🇺",
      ulke_kodu: "7",
      umuma_mahsus: "✅ (UP TO 60 DAYS)",
      resmi_pasaport: "✅ (UP TO 60 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 157,
      ulke: "Saint Kitts and Nevis",
      cca2: "KN",
      bayrak: "🇰🇳",
      ulke_kodu: "1869",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 158,
      ulke: "Saint Lucia",
      cca2: "LC",
      bayrak: "🇱🇨",
      ulke_kodu: "1758",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 159,
      ulke: "Saint Vincent and the Grenadines",
      cca2: "VC",
      bayrak: "🇻🇨",
      ulke_kodu: "1784",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 160,
      ulke: "San Marino",
      cca2: "SM",
      bayrak: "🇸🇲",
      ulke_kodu: "378",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 161,
      ulke: "São Tomé and Príncipe",
      cca2: "ST",
      bayrak: "🇸🇹",
      ulke_kodu: "239",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 162,
      ulke: "Senegal",
      cca2: "SN",
      bayrak: "🇸🇳",
      ulke_kodu: "221",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 163,
      ulke: "Seychelles",
      cca2: "SC",
      bayrak: "🇸🇨",
      ulke_kodu: "248",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 164,
      ulke: "Serbia",
      cca2: "RS",
      bayrak: "🇷🇸",
      ulke_kodu: "381",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 165,
      ulke: "Sierra Leone",
      cca2: "SL",
      bayrak: "🇸🇱",
      ulke_kodu: "232",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 166,
      ulke: "Singapore",
      cca2: "SG",
      bayrak: "🇸🇬",
      ulke_kodu: "65",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 167,
      ulke: "Slovakia",
      cca2: "SK",
      bayrak: "🇸🇰",
      ulke_kodu: "421",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 168,
      ulke: "Slovenia",
      cca2: "SI",
      bayrak: "🇸🇮",
      ulke_kodu: "386",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 169,
      ulke: "Solomon Islands",
      cca2: "SB",
      bayrak: "🇸🇧",
      ulke_kodu: "677",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 170,
      ulke: "Somalia",
      cca2: "SO",
      bayrak: "🇸🇴",
      ulke_kodu: "252",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 171,
      ulke: "Sri Lanka",
      cca2: "LK",
      bayrak: "🇱🇰",
      ulke_kodu: "94",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 172,
      ulke: "Sudan",
      cca2: "SD",
      bayrak: "🇸🇩",
      ulke_kodu: "249",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 173,
      ulke: "Suriname",
      cca2: "SR",
      bayrak: "🇸🇷",
      ulke_kodu: "597",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 174,
      ulke: "Syria",
      cca2: "SY",
      bayrak: "🇸🇾",
      ulke_kodu: "963",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 175,
      ulke: "Saudi Arabia",
      cca2: "SA",
      bayrak: "🇸🇦",
      ulke_kodu: "966",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 176,
      ulke: "Swaziland",
      cca2: "SZ",
      bayrak: "🇸🇿",
      ulke_kodu: "268",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 177,
      ulke: "Chile",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
      cca2: "CL",
      bayrak: "🇨🇱",
      ulke_kodu: "56",
    },
    {
      id: 178,
      ulke: "Tajikistan",
      cca2: "TJ",
      bayrak: "🇹🇯",
      ulke_kodu: "992",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 60 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 179,
      ulke: "Tanzania",
      cca2: "TZ",
      bayrak: "🇹🇿",
      ulke_kodu: "255",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 180,
      ulke: "Thailand",
      cca2: "TH",
      bayrak: "🇹🇭",
      ulke_kodu: "66",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 181,
      ulke: "Republic of China (Taiwan)",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
      cca2: "TW",
      bayrak: "🇹🇼",
      ulke_kodu: "886",
    },
    {
      id: 182,
      ulke: "Togo",
      cca2: "TG",
      bayrak: "🇹🇬",
      ulke_kodu: "228",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 183,
      ulke: "Tonga",
      cca2: "TO",
      bayrak: "🇹🇴",
      ulke_kodu: "676",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 184,
      ulke: "Trinidad and Tobago",
      cca2: "TT",
      bayrak: "🇹🇹",
      ulke_kodu: "1868",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 185,
      ulke: "Tunisia",
      cca2: "TN",
      bayrak: "🇹🇳",
      ulke_kodu: "216",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 186,
      ulke: "Tuvalu",
      cca2: "TV",
      bayrak: "🇹🇻",
      ulke_kodu: "688",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⛔️",
    },
    {
      id: 187,
      ulke: "Turkmenistan",
      cca2: "TM",
      bayrak: "🇹🇲",
      ulke_kodu: "993",
      umuma_mahsus: "✅ (UP TO 30 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 188,
      ulke: "Uganda",
      cca2: "UG",
      bayrak: "🇺🇬",
      ulke_kodu: "256",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 189,
      ulke: "Ukraine",
      cca2: "UA",
      bayrak: "🇺🇦",
      ulke_kodu: "380",
      umuma_mahsus: "✅ (UP TO 60 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 190,
      ulke: "Oman",
      cca2: "OM",
      bayrak: "🇴🇲",
      ulke_kodu: "968",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 191,
      ulke: "Uruguay",
      cca2: "UY",
      bayrak: "🇺🇾",
      ulke_kodu: "598",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 192,
      ulke: "Jordan",
      cca2: "JO",
      bayrak: "🇯🇴",
      ulke_kodu: "962",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 193,
      ulke: "Vanuatu",
      cca2: "VU",
      bayrak: "🇻🇺",
      ulke_kodu: "678",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 194,
      ulke: "Vatican City",
      cca2: "VA",
      bayrak: "🇻🇦",
      ulke_kodu: "3906698",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 195,
      ulke: "Venezuela",
      cca2: "VE",
      bayrak: "🇻🇪",
      ulke_kodu: "58",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 196,
      ulke: "Vietnam",
      cca2: "VN",
      bayrak: "🇻🇳",
      ulke_kodu: "84",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 197,
      ulke: "Yemen",
      cca2: "YE",
      bayrak: "🇾🇪",
      ulke_kodu: "967",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "✅ (UP TO 30 DAYS)",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 198,
      ulke: "New Zealand",
      cca2: "NZ",
      bayrak: "🇳🇿",
      ulke_kodu: "64",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 199,
      ulke: "Greece",
      cca2: "GR",
      bayrak: "🇬🇷",
      ulke_kodu: "30",
      umuma_mahsus: "✅ (UP TO 90 DAYS)",
      resmi_pasaport: "✅ (UP TO 90 DAYS)",
      e_vize: "⛔️",
    },
    {
      id: 200,
      ulke: "Zambia",
      cca2: "ZM",
      bayrak: "🇿🇲",
      ulke_kodu: "260",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
    {
      id: 201,
      ulke: "Zimbabwe",
      cca2: "ZW",
      bayrak: "🇿🇼",
      ulke_kodu: "263",
      umuma_mahsus: "⛔️",
      resmi_pasaport: "⛔️",
      e_vize: "⚠️ CONDITIONAL ✅",
    },
  ];